### ISSUE TITLE
IMDb captcha when logging in

### ISSUE THREAD

**Issue by trolin522581** [StegSchreck/RatS#260] opened 2023-10-05 17:04 UTC
**Describe the bug**
I'm using your latest Docker image to access IMDb. Authentication to IMDb fails due to a CAPTCHA. Note that there is no visible CAPTCHA when logging in to IMDb manually.

**To Reproduce**
I ran this command:
docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source imdb

**Expected behavior**
Normal command completion and exit

**Desktop (please complete the following information):**
- Version: latest (as of today)
- Platform OS: MacOS 11.7.10 (Big Sur) Intel
- Running in Docker?: yes
- Executed command: see above

## Console output
```
2023-10-05 10:23:07 ===== IMDB: performing login
2023-10-05 10:23:07 ERROR: Login to IMDB failed.
2023-10-05 10:23:07 There seems to be a Captcha challenge present for the login. Please try again later.
2023-10-05 10:23:07 
2023-10-05 10:23:07 
2023-10-05 10:23:07 ===== ABORTING =====
```

**Additional context**
Consistently repeatable

**Comment by StegSchreck** [comment] 2023-10-05 18:05
duplicate of #43

**Closed by StegSchreck** 2023-10-05 18:05 UTC
