### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by michomuchomacho** [StegSchreck/RatS#1] opened 2017-07-07 12:02 UTC
Hi, I've been trying to get the script to work with no luck. I was able to circumnavigate certain errors by forcing the bash to use python3, otherwise this error qould appear:
`TypeError: super() argument 1 must be type, not classobj`

But in the end I got stuck here:

```
python3 transfer_ratings.py --source trakt --destination tmdb
===== Trakt: performing loginTraceback (most recent call last):
  File "./RatS/RatS/parsers/base_parser.py", line 21, in parse
    self._parse_ratings()
  File "./RatS/RatS/parsers/base_parser.py", line 31, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "./RatS/RatS/parsers/trakt_parser.py", line 22, in _get_pages_count
    return int(movie_ratings_page.find(id='rating-items').
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ratings.py", line 120, in <module>
    main()
  File "transfer_ratings.py", line 53, in main
    execute(args)
  File "transfer_ratings.py", line 90, in execute
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 99, in parse_data_from_source
    movies = parser.parse()
  File "./RatS/RatS/parsers/base_parser.py", line 24, in parse
    self._parse_ratings()
  File "./RatS/RatS/parsers/base_parser.py", line 31, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "./RatS/RatS/parsers/trakt_parser.py", line 22, in _get_pages_count
    return int(movie_ratings_page.find(id='rating-items').
AttributeError: 'NoneType' object has no attribute 'find_all'
```

And, since I'm no pro, I can't figure out any more fixes... Any idea what's happening?

**Comment by StegSchreck** [comment] 2017-07-07 13:46
Hey. Thanks for your feedback! I added the Python3 requirement to the readme.
About your error message: similar things happened to me, when the browser or the website (in this case trakt) was slow and the parser tried to read HTML elements, which were not there yet. The second part of the stacktrace is the retry of the parsing.
I just increased the sleep time before this step a little. You might still run into this error though. If you want to help me investigate, you can run the script with the option `-x` in order to see what actually happens in the browser. Please send me a screenshot and the sourcecode of the page where the script gets stuck.

**Comment by michomuchomacho** [comment] 2017-07-12 14:09
Hi, sorry for the late answer.

I attributed my failures to my use of the Windows Subsystem for Linux
instead of a real Linux Distro, so I went ahead and tried at home with an
Ubuntu laptop.
This time I didn't even get that far, I wonder why...

I didn't record the error, as I was in a hurry, I'm sorry. I hope you'll
have more luck with more expert testers, as I really had no idea whatsoever
about what I was doing the whole way. I usually just tinker until it works
or I get mad. This time I got mad.

Anyway, I'm kinda giving up on the "Trakt export" matter. So, until fury
for not being able to sync Trakt and TMDB kicks in again, I won't be
looking for solutions.

Thanks anyway for the help!



2017-07-07 15:46 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-07-12 15:37
Hey. 
Sorry to hear, that it didn't work on your Ubuntu either. 
I hope you will try my solution again soon. If there is any issue again, feel free to contact me. I would be happy to resolve your issue and help you making the sync work.
As I can't reproduce your problem, please understand, that I will close this issue. Feel free to re-open it, as soon as you have new insights about the conditions why this happens.

Best regards.

**Closed by StegSchreck** 2017-07-12 15:37 UTC

**Comment by StegSchreck** [comment] 2017-07-22 21:42
Hey again. 
There is a docker image of this project now. Maybe you will find this helpful.

Best regards

**Comment by michomuchomacho** [comment] 2017-07-31 14:08
Hey!
Thanks for the tip, I tried once more with docker (cool little thing,
didn't know that!), but I still get an error.

[from windows powershell and docker installed]:

======================================================

C:\Users\Mememe>docker pull stegschreck/rats
Using default tag: latest
latest: Pulling from stegschreck/rats
75c416ea735c: Pull complete
c6ff40b6d658: Pull complete
a7050fc1f338: Pull complete
f0ffb5cf6ba9: Pull complete
be232718519c: Pull complete
a267c2cd16ea: Pull complete
c01da53c2b4a: Pull complete
d0accd2965ec: Pull complete
3cf89bda6bb9: Pull complete
696d50e87d54: Pull complete
cf497565f21d: Pull complete
77a68f97b960: Pull complete
7f58cecb2d1c: Pull complete
586d7dad640a: Pull complete
0dbf4f986150: Pull complete
d63ce20e11f0: Pull complete
d2942e7fc782: Pull complete
90f9fd00e7f0: Pull complete
53b2ee185f2b: Pull complete
294e5d294ec9: Pull complete
0f2fd8a4ee09: Pull complete
403aec92a220: Pull complete
Digest:
sha256:ea58fed3f919ce05fe8a3b39cd39ce5a9933b4f6551859551f6135352ec76a2a
Status: Downloaded newer image for stegschreck/rats:latest

C:\Users\Mememe>docker run -it -v ./RatS.cfg:/RatS/RatS/credentials.cfg
stegschreck/rats python3 transfer_ratings.py --source trakt --destination
imdb
===== Trakt: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 125, in <module>
    main()
  File "transfer_ratings.py", line 56, in main
    execute(args)
  File "transfer_ratings.py", line 95, in execute
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 104, in parse_data_from_source
    movies = parser.parse()
  File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 32, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 23, in
_get_pages_count
    find_all('li', class_='page')[-1].find('a').get_text())
IndexError: list index out of range

==========================================================

I think it's the same error I got last time (the one i couldn't record).
Also, I got it to work from ubuntu bash to and fro IMDB and TMDB (whereas
with docker it won't work)
Could it be a problem with the Trakt parser?


2017-07-22 23:42 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by michomuchomacho** [comment] 2017-07-31 14:14
Since I was into it, I tried again with the Ubuntu Bash and got this error:

=========================================================

python3 transfer_ratings.py --source trakt --destination imdb
===== Trakt: performing loginTraceback (most recent call last):
  File "/mnt/c/Users/Mememe/RatS/RatS/base/base_ratings_parser.py", line
21, in parse
    self._parse_ratings()
  File "/mnt/c/Users/Mememe/RatS/RatS/base/base_ratings_parser.py", line
32, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "/mnt/c/Users/Mememe/RatS/RatS/trakt/trakt_ratings_parser.py", line
22, in _get_pages_count
    return int(movie_ratings_page.find(id='rating-items').
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ratings.py", line 125, in <module>
    main()
  File "transfer_ratings.py", line 56, in main
    execute(args)
  File "transfer_ratings.py", line 95, in execute
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 104, in parse_data_from_source
    movies = parser.parse()
  File "/mnt/c/Users/Mememe/RatS/RatS/base/base_ratings_parser.py", line
24, in parse
    self._parse_ratings()
  File "/mnt/c/Users/Mememe/RatS/RatS/base/base_ratings_parser.py", line
32, in _parse_ratings
    pages_count = self._get_pages_count(movie_ratings_page)
  File "/mnt/c/Users/Mememe/RatS/RatS/trakt/trakt_ratings_parser.py", line
22, in _get_pages_count
    return int(movie_ratings_page.find(id='rating-items').
AttributeError: 'NoneType' object has no attribute 'find_all'

========================================================

Hope it helps to identify possible problems!

**Comment by StegSchreck** [comment] 2017-08-09 16:56
Hey again. I just was on holidays, so sorry for the late answer. 

I think I could reproduce the problem you are facing. When there is only one page of ratings, a certain web element (the pagination) is not present, which the script is expecting. This would explain the `list index out of range` error. I made a workaround for this and would like to ask you to try it again. 
The second thing you posted sounds like a different problem. A certain web element is not there, but even if you have no ratings at all, it definitely should be displayed. Nevertheless I built in a fallback for that, too. But I'm not sure about the effect it will have. 

Can you tell me how many movies you have rated in trakt so far?

Best regards.

**Comment by michomuchomacho** [comment] 2017-08-10 07:22
Hi! I Hope you had a nice vacation! (nevermind late answers, programmers
are like wizards: never late, nor early. Just precisely when they mean to.
XD)

I have 1,451 ratings, could it be overload?

Anyway, I tried to import (with docker) to imdb and tmdb but got these
errors:

========================================================
TRAKT TO IMDB:
docker run -it -v /.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats
python3 transfer_ratings.py --source trakt --destination imdb
===== Trakt: Parsing 1 pages with 0 movies in total
===== Trakt: Parsing 1 pages with 0 movies in total
Traceback (most recent call last):
  File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/RatS/RatS/base/base_ratings_parser.py", line 56, in
_parse_movie_listing_page
    movies_tiles = self._get_movie_tiles(movie_listing_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in
_get_movie_tiles
    return movie_listing_page.find(class_='row posters').find_all('div',
attrs={'data-type': 'movie'})
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ratings.py", line 125, in <module>
    main()
  File "transfer_ratings.py", line 56, in main
    execute(args)
  File "transfer_ratings.py", line 95, in execute
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 104, in parse_data_from_source
    movies = parser.parse()
  File "/RatS/RatS/base/base_ratings_parser.py", line 24, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/RatS/RatS/base/base_ratings_parser.py", line 56, in
_parse_movie_listing_page
    movies_tiles = self._get_movie_tiles(movie_listing_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in
_get_movie_tiles
    return movie_listing_page.find(class_='row posters').find_all('div',
attrs={'data-type': 'movie'})
AttributeError: 'NoneType' object has no attribute 'find_all'

TRAKT TO TMDB:
docker run -it -v /.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats
python3 transfer_ratings.py --source trakt --destination tmdb
===== Trakt: Parsing 1 pages with 0 movies in total
===== Trakt: Parsing 1 pages with 0 movies in total
Traceback (most recent call last):
  File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/RatS/RatS/base/base_ratings_parser.py", line 56, in
_parse_movie_listing_page
    movies_tiles = self._get_movie_tiles(movie_listing_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in
_get_movie_tiles
    return movie_listing_page.find(class_='row posters').find_all('div',
attrs={'data-type': 'movie'})
AttributeError: 'NoneType' object has no attribute 'find_all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ratings.py", line 125, in <module>
    main()
  File "transfer_ratings.py", line 56, in main
    execute(args)
  File "transfer_ratings.py", line 95, in execute
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 104, in parse_data_from_source
    movies = parser.parse()
  File "/RatS/RatS/base/base_ratings_parser.py", line 24, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/RatS/RatS/base/base_ratings_parser.py", line 56, in
_parse_movie_listing_page
    movies_tiles = self._get_movie_tiles(movie_listing_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in
_get_movie_tiles
    return movie_listing_page.find(class_='row posters').find_all('div',
attrs={'data-type': 'movie'})
AttributeError: 'NoneType' object has no attribute 'find_all'

==================================================================

Thanks for the help!

2017-08-09 18:56 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-10 09:43
![wizard](https://vignette2.wikia.nocookie.net/simpsons/images/f/fe/Wizard.jpg/revision/latest?cb=20120622020658)


`Trakt: Parsing 1 pages with 0 movies in total`
This line says, that he could find any movies at all in your Trakt account, which seems weird. I don't understand that behavior right now.

A higher number of rated movie should not be an issue. 1451 is roughly the same number I already tested with.

How exactly is your setup? which operating system are you using?

**Comment by michomuchomacho** [comment] 2017-08-10 10:20
Hi again!

I'm on a Windows 10 64bit Desktop running Docker!
(all the tests done with ubuntu --minus one-- where also made here with the
Ubuntu Bash, a new addition to W10)

When it ran, I thought that those parsings with 0 movies could be from
other trakt auto-generated lists (if they exists at all) that I don'y use,
since there were two entries with 0 movies found. I don't know if it's
possible.

2017-08-10 11:43 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-10 11:30
Well the script is designed to go to the ratings list of the user. Which is https://trakt.tv/users/<your_username>/ratings/movies/all/added
This is in fact not one of your self-defined watchlists, but a page, where all your ratings are displayed. You can also reach this page via the menu in the top right corner (hover over your username) -> ratings

**Comment by michomuchomacho** [comment] 2017-08-10 11:43
Ok, so it is populated: 1,131 movies (the difference being rated tv-shows
chapters, which I don't care about).
It's a mistery, then!

I thought it could be because of the private checkbox I read about
somewhere, but my list is public :/


2017-08-10 13:30 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-10 12:13
Well, that was exactly the point of this script, that it doesn't care about if the ratings are private or not.

I am really puzzled right now. In fact, I didn't test it on Win10 or the Ubuntu bash in it, because I don't own a system running Win10 sadly.

I will try to setup a VM in order to test this issue.

**Comment by michomuchomacho** [comment] 2017-08-10 12:42
The Ubuntu Bash bit is really just due to my working with a Windows system
at work and having little to no time to try this at home with a Linux
system. But it's so widely unknown that you could overlook it without
regrets.
Docker, on the other hand, *should *work without too big a difference on
Windows, Linux, etc. I'd focus on that.

Anyway thanks a lot a lot a lot again!

2017-08-10 14:13 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-10 18:06
That's true. Docker *should* work, as it abstracts from your actual operating system.
No need to thank me. The problem you are facing isn't fixed yet, is it?

**Comment by michomuchomacho** [comment] 2017-08-11 07:01
Nope, I still get the same error with docker.
I *think* I'm using it the right way, from either cmd.exe or powershell.
Can you confirm that? Being new to docker i could't say.

2017-08-10 20:06 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-11 07:44
Which Windows edition is it? I think I read somewhere, that containers are not available on all win editions.

You did install Docker for Windows, right? https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

**Comment by michomuchomacho** [comment] 2017-08-11 07:59
Yeah, yeah I did :P
I'm on Windows 10 64bit (with the last updates as far as I know)!

2017-08-11 9:44 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment] 2017-08-11 08:21
sorry for asking, just wanted the exclude that possibility

**Comment by StegSchreck** [comment] 2017-08-14 17:47
I could reproduce the problem. I created a new ticket for it and will have a deeper look soon.
--> #19
