### ISSUE TITLE
Trakt - AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by 4everfun** [StegSchreck/RatS#55] opened 2018-09-22 13:22 UTC
`python3.6 transfer_ratings.py --source trakt --destination movielens`

Whenever I am trying to login to Trakt, I get this error.

It happens when I locally execute it with python3.6 and even in the docker. Any clue what this could be? If you need any more information feel free to ask

```
===== Trakt: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 111, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 133, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 138, in parse_data_from_source
    movies = parser.parse()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 34, in parse
    raise e
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 30, in parse
    self._parse_ratings()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 46, in _parse_ratings
    self.movies_count = self._get_movies_count(movie_ratings_page)
  File "/opt/RatS/RatS/trakt/trakt_ratings_parser.py", line 16, in _get_movies_count
    return int(movie_ratings_page.find('section', class_='subnav-wrapper').
AttributeError: 'NoneType' object has no attribute 'find'

```

**Comment by 4everfun** [comment] 2018-09-22 18:01
Tried it again, issue still persists.

**Comment by StegSchreck** [comment] 2018-09-23 07:44
Thanks for your message. Unfortunately, I couldn't reproduce the error. could you please run the script again with `-vvv` to have a more detailed log and attach the last lines before the error here. Additionally you could try to use the `-x` option to tell me on which page the script gets stuck.

I assume there is a problem when getting the source for the website (in base_ratings_parser.py:42), but I can't say why currently.

**Comment by 4everfun** [comment] 2018-09-25 15:33
Not sure if I'm doing this correctly.

Executing:
`docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination movielens -x`

Which gives:
```Traceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 9, in __init__
    super(TraktRatingsParser, self).__init__(Trakt(args), args)
  File "/RatS/RatS/trakt/trakt_site.py", line 10, in __init__
    super(Trakt, self).__init__(args)
  File "/RatS/RatS/base/base_site.py", line 32, in __init__
    self._init_browser()
  File "/RatS/RatS/base/base_site.py", line 58, in _init_browser
    self.browser_handler = BrowserHandler(self.args)
  File "/RatS/RatS/utils/browser_handler.py", line 30, in __init__
    log_path="{timestamp}_geckodriver.log".format(timestamp=TIMESTAMP)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1```

-vvv does not seem to do anything. Where would I place it?

**Comment by StegSchreck** [comment] 2018-09-25 17:11
Hey again.
Sorry for the confusion. The `-x` option does not work when working in the docker environment, but only when running natively on the command line, as it tries to display the browser. The `-vvv` is an argument for the transfer_ratings.py, so you can add this anywhere after that, e.g. at the complete end:
`docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination movielens -vvv`

Thanks for your help resolving this issue.

**Comment by 4everfun** [comment] 2018-09-26 07:45
No problem! The command you listed gives the same exact error as my first post. Anything else I can do?

**Comment by StegSchreck** [comment] 2018-09-26 13:11
Did you try to run it without docker, but with the `-x` parameter to see the browser? Maybe this gives a hint of where and why he is failing.

**Comment by 4everfun** [comment] 2018-09-26 13:21
I did not since I run it on a headless server, I hope this isn't a problem?

**Comment by 4everfun** [comment] 2018-09-30 11:46
I'm currently using Ubuntu 18.04. Will try to install xvfb later this week, I'll let you know!

**Closed** 2018-10-26 14:59 UTC
Labels: bug, question

**Comment by keldian** [comment] 2020-01-11 13:29
I'm having this issue as well.

`===== Trakt: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 227, in <module>
    main()
  File "transfer_ratings.py", line 79, in main
    execute(args)
  File "transfer_ratings.py", line 128, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 171, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 177, in parse_data_from_source
    movies = parser.parse()
  File "/RatS/RatS/base/base_ratings_parser.py", line 37, in parse
    raise e
  File "/RatS/RatS/base/base_ratings_parser.py", line 33, in parse
    self._parse_ratings()
  File "/RatS/RatS/base/base_ratings_parser.py", line 48, in _parse_ratings
    pages_count = self._retrieve_pages_count_and_movies_count(movie_ratings_page)
  File "/RatS/RatS/base/base_ratings_parser.py", line 79, in _retrieve_pages_count_and_movies_count
    self.movies_count = self._get_movies_count(movie_ratings_page)
  File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 16, in _get_movies_count
    return int(movie_ratings_page.find('section', class_='subnav-wrapper').
AttributeError: 'NoneType' object has no attribute 'find'
`

Tried on Ubuntu 18.04 and Fedora 31, xvfb installed, with or without docker. Same error every time.

**Comment by StroescuTheo** [comment] 2020-03-14 10:39
I had this issue too when trying to sync trakt and imdb. I ran the command using the -x flag to see the steps in my browser. I noticed the problem was that the script is searching for titles using links generated from the username in credentials. I was using my email as a login username but it differs from the username associated with the trakt account, and those links require that username.
You can go to your profile to see this exact username. After changing it in the credentials file it works perfectly.

**Comment by StegSchreck** [comment] 2020-03-24 19:32
Hey @StroescuTheo 
Thank you for this detailed example. That is very useful!
